# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests and build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SECRET: thisisatest
  GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
  GOOGLE_SECRET: ${{secrets.GOOGLE_SECRET}}

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: api/package-lock.json
        
      - name: Install project dependencies (NPM)
        run: npm ci
        working-directory: ./api

      - name: UNIT TEST (JEST)
        run: npm run test
        working-directory: ./api

  build-frontend-bundle:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: api/package-lock.json

      - name: Install project dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Test frontend build
        run: npm run build
        working-directory: ./frontend
